apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: nsgr
  name: rootapp
  labels:
    app: rootapp
spec:
  template:
    metadata:
      labels:
        app: rootapp
        tier: web
    spec:
      containers:
        - name: rootapp
          image: gymrabbit/rootapp:KVERSION
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: nsgr
  name: rootapp
  labels:
    app: rootapp
spec:
  type: NodePort
  selector:
    app: rootapp
    tier: web
  ports:
    - port: 8080
      targetPort: 8080